Repository WANTED-TEAM03/pre-onboarding-10th-2-3, pull requests merged in 2023-05, with the labels that each got.

#2 [FEAT] : 검색창 UI 마크업 및 스타일링
  package.json
  src/components/SearchSection/SearchBar/DeleteButton/index.tsx
  src/components/SearchSection/SearchBar/index.tsx
  src/components/SearchSection/SearchIcon/index.tsx
  src/components/SearchSection/SearchWordBox/SearchWord/index.tsx
  src/components/SearchSection/SearchWordBox/index.tsx
  src/components/SearchSection/index.tsx
  src/constants/searchWord.ts
Labels: FEAT

#4 검색어 저장 캐시 스토리지, 최근 검색어 저장 세션 스토리지 유틸 함수 작성
  src/components/SearchSection/index.tsx
  src/constants/cache.ts
  src/constants/session.ts
  src/hooks/.gitkeep
  src/hooks/useRecentSearchWords.ts
  src/types/index.d.ts
  src/utils/.gitkeep
  src/utils/cacheStorage.ts
Labels: FEAT

#6 추천 검색어 API 및 캐시 저장 기능 구현
  src/components/SearchSection/SearchWordBox/index.tsx
  src/services/.gitkeep
  src/services/apiClient.ts
  src/services/search.ts
Labels: FEAT

#8 디바운스를 통한 API 호출 최소화
  src/components/SearchSection/SearchWordBox/index.tsx
  src/hooks/useDebounce.ts
Labels: FEAT

#10 키보드 네비게이션 구현
  .gitignore
  .vscode/settings.json
  src/components/SearchSection/SearchBar/index.tsx
  src/components/SearchSection/SearchWordBox/SearchWord/index.tsx
  src/components/SearchSection/SearchWordBox/index.tsx
  src/components/SearchSection/index.tsx
  src/constants/config.ts
Labels: FEAT, REFACTOR

#12 [FIX] : 추천 검색어, 방향키 이동 이슈 해결 및 검색어 재입력 시 focusIndex 리셋
  src/components/SearchSection/SearchBar/index.tsx
  src/components/SearchSection/SearchWordBox/SearchWord/index.tsx
  src/components/SearchSection/SearchWordBox/index.tsx
  src/components/SearchSection/index.tsx
  src/constants/config.ts
Labels: FIX, REFACTOR

#14 [REFACTOR] : 변수 네이밍 수정, keyDown 이벤트 커스텀훅 추가
  src/components/SearchSection/SearchBar/DeleteButton/index.tsx
  src/components/SearchSection/SearchBar/index.tsx
  src/components/SearchSection/SearchWordBox/SearchWord/index.tsx
  src/components/SearchSection/SearchWordBox/index.tsx
  src/components/SearchSection/index.tsx
  src/constants/cache.ts
  src/constants/config.ts
  src/hooks/useKeyFocus.ts
  src/hooks/useRecentSearchWords.ts
  src/services/search.ts
  src/utils/cacheStorage.ts
Labels: REFACTOR

#17 포커스 스타일링 통일 및 검색 대소문자 이슈 해결
  src/components/SearchSection/SearchWordBox/SearchWord/index.tsx
  src/components/SearchSection/SearchWordBox/index.tsx
  src/components/SearchSection/index.tsx
Labels: FIX

#18 [DOCS] : README.md 작성
  README.md
Labels: DOCS

#20 netlify 배포 proxy 추가
  netlify.toml
  src/constants/config.ts
Labels: FIX

#21 netlify 배포
  README.md
  netlify.toml
  src/constants/config.ts
Labels: RELEASE
